### ISSUE TITLE
m7m : Undefined symbol ... driving me nuts :)

### ISSUE THREAD

**Issue by alexandre-romain** [foxer666/node-multi-hashing#5]
Hi Alex,

i'm Alex ;)

There are some days I try to run a pool for magi coins.

I did manage to set it up, but whatever I use (NOMP, uNOMP, any of the multi-hashing modules I find ..), after adding m7m algo and rebuilding it, I always end with the same problem which is (or similar) :

2018-03-07 10:13:37 [Switching] [Setup] (m7m) Setting proxy difficulties after pool start
/home/magi/.nvm/versions/node/v8.9.4/bin/node: symbol lookup error: /home/magi/nomp/node_modules/stratum-pool/node_modules/multi-hashing/build/Release/multihashing.node: undefined symbol: sph_haval256_5_init

Any idea of what I could do to fix this ?

Thanks a lot in advance !!

**Comment by devnull-ed** [comment]
Something with calls in node-multi-hashing, just dealing with similar issue on neoscrypt. I'll write when i find the reason

**Comment by alexandre-romain** [comment]
In the comments of the makefile, 'they' speak of circular dependencies, which is probably the problem.
They use --start-group to fix the 'problem'. Unfortunately, I have no idea about what to do with this :'(


# Due to circular dependencies between libraries :(, we wrap the
# special "figure out circular dependencies" flags around the entire
# input list during linking.
quiet_cmd_link = LINK($(TOOLSET)) $@
cmd_link = $(LINK.$(TOOLSET)) $(GYP_LDFLAGS) $(LDFLAGS.$(TOOLSET)) -o $@ -Wl,--start-group $(LD_INPUTS) -Wl,--end-group $(LIBS)

**Comment by devnull-ed** [comment]
Its not the makefile of the project, its getting generated by Node

**Comment by alexandre-romain** [comment]
I'll wait for news from you .. :)

**Comment by devnull-ed** [comment]
This seems to be problem with linker. You do not link it correctly. In my case, it was asm implementation of neoscrypt, which I does not cook properly. Working on it.

Have at look in bindings.gyp, probably you just missed declaration there.

**Comment by alexandre-romain** [comment]
Here's my bindings.gyp, I did nothing but add the 2 lines concerning m7m algo : 

```
{
    "targets": [
        {
            "target_name": "multihashing",
            "sources": [
                "m7m/magimath.c",
                "m7m/m7m.c",
                "multihashing.cc",
                "bcrypt.c",
                "blake.c",
                "boolberry.cc",
                "c11.c",
                "cryptonight.c",
                "dcrypt.c",
                "fresh.c",
                "fugue.c",
                "groestl.c",
                "hefty1.c",
                "keccak.c",
                "lyra2.c",
                "lyra2re.c",
                "lyra2z.c",
                "neoscrypt.c",
                "nist5.c",
                "quark.c",
                "qubit.c",
                "s3.c",
                "scryptjane.c",
                "scryptn.c",
                "shavite3.c",
                "skein.c",
                "Sponge.c",
                "tribus.c",
                "sha1.c",
                "sha3/sph_hefty1.c",
                "sha3/sph_fugue.c",
                "sha3/aes_helper.c",
                "sha3/sph_blake.c",
                "sha3/sph_bmw.c",
                "sha3/sph_cubehash.c",
                "sha3/sph_echo.c",
                "sha3/sph_groestl.c",
                "sha3/sph_jh.c",
                "sha3/sph_keccak.c",
                "sha3/sph_luffa.c",
                "sha3/sph_shavite.c",
                "sha3/sph_simd.c",
                "sha3/sph_skein.c",
                "sha3/sph_whirlpool.c",
                "sha3/sph_shabal.c",
                "sha3/hamsi.c",
                "whirlpoolx.c",
                "x11.c",
                "x11ghost.c",
                "x13.c",
                "x14.c",
                "x15.c",
                "zr5.c",
                "crypto/oaes_lib.c",
                "crypto/c_keccak.c",
                "crypto/c_groestl.c",
                "crypto/c_blake256.c",
                "crypto/c_jh.c",
                "crypto/c_skein.c",
                "crypto/hash.c",
                "crypto/aesb.c",
                "crypto/wild_keccak.cpp",
            ],
            "include_dirs": [
                "crypto",
                "<!(node -e \"require('nan')\")"
            ],
            "cflags_cc": [
                "-std=c++0x"
            ],
        }
    ]
}
```

**Comment by devnull-ed** [comment]
Can I close it?

**Comment by alexandre-romain** [comment]
Never found any solution ... MAGI support sadly ain't sufficient
